### PR TITLE
Mike Armstrong: Not finished BTW. I have modified the code I used in class for learning recyclerviews to s...

### PR DESCRIPTION
**Pull request by armstrxng**
...tart the assignment. Mapping the string value for the artists is done, however I'm not sure how to get their associated album arts to display behind the string.

### CODE REVIEW

**Comment by sstutsman** [comment]
There is a submodule in your repository instead of the code itself. I'm unable to access this and can't grade it -- please remove the project from the submodule and push up to your repository itself.

**Comment by armstrxng** [comment]
I can't seem to push anything up without pulling first. When I pull it puts
in that submodule. Should I just delete my repository and refork the
project?

**Comment by sstutsman** [comment]
Yeah... Forget the git history for now and just give me that code. Quickly, please.

**Comment by armstrxng** [comment]
Okay so I uploaded it again, however the only way I found so that you can
see the code was if I just put the program directly in the assignment-three
folder without a folder named armstrxng.

**Pull request closed without merging**
